[env:node32s]
platform = espressif32
board = node32s
framework = arduino
upload_port = COM4
upload_speed = 115200
upload_flags =
	--before
	default_reset
	--after
	hard_reset
monitor_port = COM4
lib_deps =
	adafruit/DHT sensor library @ ^1.4.6
	adafruit/Adafruit Unified Sensor @ ^1.1.15
	knolleary/PubSubClient @ ^2.8
	bblanchon/ArduinoJson @ ^7.3.1

; Tambahkan baris ini untuk menyamakan kecepatan Serial Monitor
monitor_speed = 115200 