[env:node32s]
platform = espressif32
board = node32s
framework = arduino

upload_speed = 115200
monitor_speed = 115200

monitor_rts = 0
monitor_dtr = 0

lib_deps =
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.15
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.3.1
